# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)


# Chatroom.create(activity_id: 1)
# Message.create(chatroom_id: 1, user_id: 1, content:'blah blah')


User.create(username:'Mocha', name:'Mokhtar', password:'1234', email: 'joemokhtarali@gmail.com',image:'')

Category.create(category_type:'Theaters', about:"Modern theatre includes performances of plays and musical theatre. The art forms of ballet and opera are also theatre and use many conventions such as acting, costumes and staging. They were influential to the development of musical theatre; see those articles for more information.") 
Category.create(category_type:'Sports', about:"Sport is generally recognised as system of activities which are based in physical athleticism or physical dexterity, with the largest major competitions such as the Olympic Games admitting only sports meeting this definition") 
Category.create(category_type:'Nature', about:"Nature, in the broadest sense, is the natural, physical, or material world or universe. 'Nature' can refer to the phenomena of the physical world, and also to life in general. The study of nature is a large, if not the only, part of science. Although humans are part of nature, human activity is often understood as a separate category from other natural phenomena.")  
Category.create(category_type:'Art galleries and Museums', about:"A Museum is an institution that cares for (conserves) a collection of artifacts and other objects of artistic, cultural, historical, or scientific importance. Many public museums make these items available for public viewing through exhibits that may be permanent or temporary.") 


Activity.create(name: 'Hamilton', rating: 5, about: 'Hamilton is a musical with music, lyrics, and book by Lin-Manuel Miranda that tells the story of American Founding Father Alexander Hamilton. Inspired by the 2004 biography Alexander Hamilton by historian Ron Chernow', date: '04/17/2020', image: 'https://upload.wikimedia.org/wikipedia/en/thumb/8/83/Hamilton-poster.jpg/220px-Hamilton-poster.jpg', address: '214 w 42nd st, new york, ny 10036', user_id: 1, category_id:1)
Activity.create(name: 'The Lion King', rating: 5, about: 'The Lion King is a musical based on the 1994 Walt Disney Animation Studios animated feature film of the same name with music by Elton John, lyrics by Tim Rice, and book by Roger Allers and Irene Mecchi, along with additional music and lyrics by Lebo M, Mark Mancina, Jay Rifkin, Julie Taymor, and Hans Zimmer.[1] Directed by Taymor, the musical features actors in animal costumes as well as giant, hollow puppets. The show is produced by Disney Theatrical Productions.', date: '04/18/2020', image: 'https://upload.wikimedia.org/wikipedia/en/thumb/5/58/The_Lion_King_Musical.svg/1200px-The_Lion_King_Musical.svg.png', address: 'Lincoln Center Plaza, New York, NY 10023', user_id: 1, category_id:1)
Activity.create(name: 'Les miserables', rating: 5, about: "Set in early 19th-century France, Les Misérables is the story of Jean Valjean, a French peasant, and his desire for redemption after serving nineteen years in jail for having stolen a loaf of bread for his sister's starving child. Valjean decides to break his parole and start his life anew after a bishop inspires him by a tremendous act of mercy, but he is relentlessly tracked down by a police inspector named Javert. Along the way, Valjean and a slew of characters are swept into a revolutionary period in France, where a group of young idealists attempt to overthrow the government at a street barricade.", date: '04/19/2020', image: 'https://www.playbillstore.com/images/Les%20Miserables%20Broadway%20Poster%20(2014%20Revival).png', address: '208 W 41st St, New York, NY 10036', user_id: 1, category_id:1)

Activity.create(name: 'Soccer', rating: 5, about: "They call it Football all over the world!!!", date: '04/17/2020', image: 'https://www.playbillstore.com/images/Les%20Miserables%20Broadway%20Poster%20(2014%20Revival).png', address: '450 W 27th St, New York, NY 10001', user_id: 1, category_id:2)
Activity.create(name: 'Bowling', rating: 5, about: "Bowling is played by 100 million people in more than 90 countries (including 70 million in the United States alone),[2] and is the subject of many video games.", date: '04/18/2020', image: 'https://www.playbillstore.com/images/Les%20Miserables%20Broadway%20Poster%20(2014%20Revival).png', address: '200 N 14th St, Brooklyn, NY 11249', user_id: 1, category_id:2)
Activity.create(name: 'Kick Axe', rating: 5, about: "Axe throwing is a sport in which the competitor throws an axe at a target, attempting to hit the bullseye as near as possible like that of the archery. Axe throwing is an event held in most lumberjack competitions. A skilled axe thrower will rotate the throwing axe exactly once throughout the flight so that the sharpened edge of the head will penetrate the target. Throwing axes are becoming popular among outdoor enthusiasts as a throwing tool.", date: '04/19/2020', image: 'https://www.playbillstore.com/images/Les%20Miserables%20Broadway%20Poster%20(2014%20Revival).png', address: '622 Degraw St, Brooklyn, NY 11217', user_id: 1, category_id:2)

Activity.create(name: 'Central Park', rating: 5, about: "Central Park was designated as a National Historic Landmark in 1963 and as a New York City scenic landmark in 1974. The park is owned by the New York City Department of Parks and Recreation (NYC Parks) but has been managed by the Central Park Conservancy since 1998, under a contract with the municipal government in a public-private partnership. The Conservancy, a non-profit organization, contributes 75% of Central Park's $65 million annual budget and is responsible for all basic care of the park.", date: '04/17/2020', address: '450 W 27th St, New York, NY 10001', user_id: 1, category_id:3, image: 'https://thenypost.files.wordpress.com/2019/12/robberies-serious-crimes-spike-in-central-park-this-year.jpg?quality=80&strip=all')
Activity.create(name: 'Astoria Park', rating: 5, about: "The park contains New York City's oldest and largest swimming pool.[2] The outdoor 54,450-square-foot (5,059 m2) pool, planned by parks commissioner Robert Moses and opened in 1936, was used for qualifying events for the 1936 and 1964 Summer Olympics.[2]", date: '04/18/2020', address: '200 N 14th St, Brooklyn, NY 11249', user_id: 1, category_id:3, image: 'https://live.staticflickr.com/919/28571869377_1579fe7ba6_b.jpg')
Activity.create(name: 'Brooklyn Bridge Park', rating: 5, about: "Brooklyn Bridge Park is overseen by the Brooklyn Bridge Park Corporation, a not-for-profit organization that operates and maintains the park, as well as oversees its construction.", date: '04/19/2020', address: '622 Degraw St, Brooklyn, NY 11217', user_id: 1, category_id:3, image: 'https://d21xlh2maitm24.cloudfront.net/nyc/Brooklyn-Bridge-Park.jpg?mtime=20190620143027')

Activity.create(name: 'The Metropolitan Museum of Art', rating: 5, about: "The Metropolitan Museum of Art was founded in 1870 for the purposes of opening a museum to bring art and art education to the American people. The Fifth Avenue building opened on February 20, 1872, at 681 Fifth Avenue.", date: '04/17/2020', address: 'The Metropolitan Museum of Art', user_id: 1, category_id:4, image: 'https://cdn.getyourguide.com/img/tour_img-1848142-146.jpg')
Activity.create(name: 'American Museum of Natural History', rating: 5, about: "The museum complex comprises 26 interconnected buildings housing 45 permanent exhibition halls, in addition to a planetarium and a library. The museum collections contain over 34 million specimens[4] of plants, animals, fossils, minerals, rocks, meteorites, human remains, and human cultural artifacts as well as specialized collections for frozen tissue and genomic and astrophysical data,", date: '04/18/2020', address: 'American Museum of Natural History', user_id: 1, category_id:4, image: 'https://dimg04.c-ctrip.com/images/350k12000000tghfn7AB9.jpg?proc=source/trip;namelogo/d_40')
Activity.create(name: 'Brooklyn Museum', rating: 5, about: "Located near the Prospect Heights, Crown Heights, Flatbush, and Park Slope neighborhoods of Brooklyn and founded in 1895, the Beaux-Arts building, designed by McKim, Mead and White, was planned to be the largest art museum in the world. The museum initially struggled to maintain its building and collection", date: '04/19/2020', address: 'Brooklyn Museum', user_id: 1, category_id:4, image: 'https://img.artrabbit.com/organisations/brooklyn-museum-of-art/images/t1f6OdxktFIX/938x546/11547460fe811da.jpg')

